---

- name: 'Install MariaDB'
  apt:
    name: 'mariadb-server'
    state: 'present'
    update_cache: True

- name: 'Install Python 3'
  apt:
    name: 'python3-pip'
    state: 'present'

- name: 'Install pymysql'
  pip:
    name: 'pymysql'
    state: 'present'
